sudo: false

language: java

notifications:
  email: false

env:
  global:
    - PATH="/tmp/proto2.4.1/bin:$PATH"

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

before_install:
  - .buildscript/build-proto.sh 2.4.1

cache:
  directories:
    - /tmp/proto2.4.1
